- Jenkinsfile
---
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/1)
> ci: add jenkins config

- src/shuttle/shuttle-out/ShuttleOut.jsx
---
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/9)
> test: update custodiam proxy address

- src/data/useTokenList.js
CU-4tqmz8
---
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/10)
> fix: add fallback ref symbol and ref name for eth and btc

- src/data/useTokenList.js
---
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/11)
> fix: ethereum to ether

- src/component/input.module.scss
- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/15)
> fix: Fix hardcode

- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/19)
> Shuttleout debug

- src/shuttle/Input.jsx
- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/24)
> feat: Otc 27

- src/shuttle/Input.jsx
- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/25)
> feat: change another name

- src/i18n/en/nav.json
- src/i18n/zh/nav.json
- src/layout/LayoutLarge.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/30)
> feat: help link

- package.json
- src/data/useHistory.js
- src/history/HistoryItem.jsx
- src/layout/Main.jsx
- src/shuttle/shuttle-in/ShuttleIn.jsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/43)
> fix: 0tc 30

- src/layout/Layout.js
- src/layout/Main.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/45)
> fix: Add redirect properly

- package.json
- yarn.lock
---
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/47)
> fix(ShuttleOut): error on shuttleout more than 999 token

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/48)
> sync master

- shuttleflow 1.1.0.html
- src/component/modal.module.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/56)
> increase zindex

- package.json
- src/history/History.jsx
- src/history/history.module.scss
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/57)
> add loading indicator

- src/caption/Form.jsx
- src/component/urlSearch.js
- src/data/tokenList.js
- src/data/useCaption.js
- src/data/useTokenList.js
- src/layout/Layout.js
- src/setupProxy.js
- src/shuttle/shuttle-out/ShuttleOut.jsx
- src/token/Choose.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/63)
> Cu h6ywtz tokenlistcaption

- package-lock.json
- package.json
- src/data/burn.js
- src/data/contract/index.js
- src/i18n/en/nav.json
- src/i18n/zh/nav.json
- src/layout/LayoutLarge.jsx
- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/76)
> burn implementation

- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/77)
> change decimal to 18

- src/data/useOperationHistory.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/80)
> fix btc token

- package-lock.json
- package.json
- shuttleflow1.2.0.html
- src/data/beCaptain.js
- src/data/burn.js
- src/data/captain.js
- src/data/getLatestMortgage.js
- src/data/useBalance.js
- src/data/useTokenList.js
- src/setupProxy.js
- src/util/address.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/85)
> support both old&new portal version in terms of address format

- src/captain/Form.jsx
- src/captain/Form.module.scss
- src/captain/FormHeader.jsx
- src/data/burn.js
- src/layout/LayoutSmall.jsx
- src/layout/UserAddress.jsx
- src/token/TokenList.jsx
- src/util/address.js
- src/util/formatNum.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/87)
> New address

- src/component/input.module.scss
- src/i18n/i18n.js
- src/layout/UserAddress.jsx
- src/shuttle/shuttle-in/ShuttleIn.module.scss
- src/shuttle/shuttle-out/ShuttleOut.jsx
- src/util/address.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/88)
> format address

- src/captain/Form.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/89)
> optionally display show mortgage

- src/util/address.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/92)
> fix for oder portal version

- src/data/useOperationHistory.js
- src/history/HistoryItem.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/96)
> replace in/out burn/mint

- src/component/Icon/Icon.jsx
- src/data/useBalance.js
- src/data/useTokenList.js
- src/history/HistoryItem.jsx
- src/history/ShuttleHistory.jsx
- src/history/ShuttleHistory.module.scss
- src/i18n/en/history-market.json
- src/i18n/en/shuttle.json
- src/i18n/zh/history-market.json
- src/i18n/zh/shuttle.json
- src/market/Market.jsx
- src/shuttle/Shuttle.jsx
- src/shuttle/ShuttleoutInput.jsx
- src/shuttle/TokenInput.jsx
- src/shuttle/shuttle-in/ShuttleIn.jsx
- src/shuttle/shuttle-out/ShuttleOut.jsx
- src/token/TokenList.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/97)
> Seperate list

- src/layout/LayoutLarge.jsx
- src/layout/LayoutLarge.module.scss
- src/layout/PrepareData.jsx
- src/token/Token.jsx
- src/token/TokenList.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/101)
> style and fix

- config-overrides.js
- package-lock.json
- package.json
- public/index.html
- src/config/chainConfig.js
- src/data/mint.js
- src/data/useOperationHistory.js
- src/layout/ChooseChain.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/109)
> git revision

- src/token/Choose.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/114)
> remove caption

- Jenkinsfile
the code will be deployed to the new machine once this commit merged into master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/119)
> ci: use a dedicated prod machine for shuttleflow

- package.json
- src/captain/FormProvider.jsx
- webpack.parts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/121)
> fix reference

- src/config/chainConfig.js
- src/data/tokenListMapper.js
- src/data/useBalance.js
- src/layout/LayoutSmall.jsx
- src/token/TokenList.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/127)
> add home page

- src/captain/Form.jsx
- src/captain/FormProvider.jsx
- src/config/chainConfig.js
- src/data/beCaptain.js
- src/data/captain.js
- src/data/tokenList.js
- src/data/tokenListMapper.js
- src/layout/Risk.jsx
- src/market/Market.jsx
- src/token/TokenList.jsx
- src/util/id.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/132)
> totalsuppply

- src/i18n/en/nav.json
- src/i18n/zh/nav.json
- src/index.js
- src/layout/Root.jsx
- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/146)
> style the block popup

- src/captain/AddToken.jsx
- src/component/TokenInput/TokenInput.jsx
- src/config/chainConfig.js
- src/data/contract/contract.js
- src/data/useCaptainInfo.js
- src/layout/LayoutLarge.jsx
- src/market/Market.jsx
- src/shuttle/Shuttle.jsx
- src/token/TokenList.jsx
- webpack.parts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/158)
> fix a couple of styles

- src/captain/Form.jsx
- src/data/tokenList.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/171)
> add polling for isOperatorFor && fix CFX in transaction history

- src/shuttle/shuttle-out/ShuttleOut.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/174)
> fix: #7hvew4(cancel the loading when user close the popup)

- src/i18n/en/shuttle-in.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/177)
> fix: i18n key

- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/178)
> fix: connect MetaMask without required input

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/179)
> ci: modify Jenkins

- src/i18n/en/shuttle-in.json
- src/i18n/zh/shuttle-in.json
- src/lib/yup/BigNumberSchema.js
- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/180)
> fix:#7qu5q5

- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/181)
> fix:#7qu6q6

- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/182)
> fix: handle the estimate error of approve

- package.json
- src/i18n/en/shuttle-in.json
- src/i18n/zh/shuttle-in.json
- src/index.js
- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/183)
> fix:#7qu6ya

- src/shuttle/shuttle-in/ShuttleInWithMM.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/184)
> fix:#7qudnw

- package.json
- src/config/config.js
- src/index.js
- src/shuttle/shuttle-out/ShuttleOut.jsx
- src/util/index.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/185)
> fix: set max value when pair is cfx to eth/bsc

- src/config/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/188)
> fix: wrong operator

- src/i18n/en/common.json
- src/i18n/zh/common.json
- src/layout/Layout.module.scss
- src/shuttle/Shuttle.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/192)
> feat: add announcement

- src/config/chainConfig.js
- src/data/useTokenList.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/195)
> feat: can not display and search unsupported or untrusted token

- src/config/chainConfig.js
- src/token/TokenList.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/196)
> fix: fix search bug

- src/data/useTokenList.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/197)
> fix: switch to btc and portal is locked, blocked

- src/shuttle/Shuttle.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/199)
> fix: i18n for shuttlein

- src/data/useTokenList.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/200)
> fix: catch the error code:-32602

- src/config/chainConfig.js
- src/data/useTokenList.js
- src/shuttle/Shuttle.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/201)
> fix: fix bugs

- src/config/config.js
- src/globalPopup/TranscationResult.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/204)
> fix(oec): add oec scan tx url to transaction

- src/globalPopup/TranscationResult.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/205)
> chore(oec): WIP: revert code

- src/globalPopup/TranscationResult.jsx
- webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/206)
> fix: webpack error

- src/captain/fields.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/shuttleflow/207)
> fix(): disable some options when shuttlein is obverse or reverse
